version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Porta para acessar a interface de gerenciamento
      - "5672:5672"   # Porta padrão AMQP
      - "1883:1883"   # Porta padrão MQTT
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-plugins.conf:/etc/rabbitmq/enabled_plugins
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_mqtt
             && rabbitmq-server"

volumes:
  rabbitmq_data:
